apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
data:
  FLASK_ENV: "production"
  DEBUG: "false"
  LOG_LEVEL: "info"
  DB_HOST: "fahd-postgres.postgres.database.azure.com"      # or cloud DB later
  DB_NAME: "flaskdb"
