apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  namespace: flask-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
  - hosts:
    - fahdtech.store
    secretName: flask-tls
  rules:
  - host: fahdtech.store
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-lb
            port:
              number: 80
