apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flask-nginx.fullname" . }}-config

data:
  FLASK_ENV: {{ .Values.env.FLASK_ENV }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL }}
  DB_HOST: {{ .Values.env.DB_HOST }}
  DB_NAME: {{ .Values.env.DB_NAME }}
