apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-app.fullname" . }}-secret
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.secret.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ .Values.secret.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | quote }}
