replicaCount: 2

image:
  repository: fahdacr.azurecr.io/flaskapp
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: nginx
  host: fahdtech.store
  tls:
    enabled: true
    secretName: flask-tls
    clusterIssuer: letsencrypt-production

resources:
  requests:
    cpu: "100m"
  limits:
    cpu: "300m"

env:
  FLASK_ENV: "production"
  DEBUG: "false"
  LOG_LEVEL: "info"
  DB_HOST: "fahd-postgres.postgres.database.azure.com"
  DB_NAME: "flaskdb"

secret:
  POSTGRES_DB: sandbox
  POSTGRES_USER: flaskuser@fahd-postgres
  POSTGRES_PASSWORD: flaskpassword
