replicaCount: 2

image:
  repository: fahdacr.azurecr.io/flaskapp
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

env:
  FLASK_ENV: "production"
  LOG_LEVEL: "info"
  DB_HOST: "fahd-postgres.postgres.database.azure.com"
  DB_NAME: "flaskdb"

resources:
  requests:
    cpu: "100m"
  limits:
    cpu: "300m"

